// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Categories struct {
	Categories []*Category `json:"categories"`
}

type Category struct {
	ID          string `json:"id"`
	ResourceURI string `json:"resource_uri"`
	Name        string `json:"name"`
	ShortName   string `json:"short_name"`
}
